### ISSUE TITLE
Install on MacBook Pro MI consistently fails at the same point

### ISSUE THREAD

**Issue by johntaylorpa** [LexPredict/lexpredict-lexnlp#59]
Here is the traceback.  Less than one year old MacBook Pro M1.  Have tried uninstalling and reinstalling scipy, numpy and other packages, no luck.  Apparently, I cannot use LexNLP on a Mac M1 then?

Error message below:

Collecting scipy==1.5.1
  Using cached scipy-1.5.1.tar.gz (25.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/johntaylor/Programming/PycharmProjects/Python_code_Examples/ORC_Scrape/virtual/bin/python3 /Users/johntaylor/Programming/PycharmProjects/Python_code_Examples/ORC_Scrape/virtual/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/tmpeedpvclp
         cwd: /private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-install-dfxm71d1/scipy
    Complete output (37 lines):
    setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-modern-metadata-p8tcxpn6'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from SciPy source directory.
    /private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-build-env-6k0_ynk3/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    /private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-build-env-6k0_ynk3/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    Traceback (most recent call last):
      File "/Users/johntaylor/Programming/PycharmProjects/Python_code_Examples/ORC_Scrape/virtual/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/johntaylor/Programming/PycharmProjects/Python_code_Examples/ORC_Scrape/virtual/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/johntaylor/Programming/PycharmProjects/Python_code_Examples/ORC_Scrape/virtual/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-build-env-6k0_ynk3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-build-env-6k0_ynk3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-build-env-6k0_ynk3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 583, in <module>
        setup_package()
      File "setup.py", line 579, in setup_package
        setup(**metadata)
      File "/private/var/folders/lk/0t8r88js023ddfc2z8s74v8m0000gn/T/pip-build-env-6k0_ynk3/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.

**Comment by bethanyleap** [comment]
Running into the same thing. Has this issue ever been addressed?

**Comment by afparsons** [comment]
We are planning on updating the SciPy requirement from 1.5.1 to a newer version in the next release in order to support Apple ARM.

Annecdotally, I have heard that manually installing SciPy resolves this issue. I believe 1.8.0 is the latest version.

**Comment by johntaylormax** [comment]
Manually installing SciPY using pip then by itself?
